[colors]
	[colors.primary]
	background = '0x000000'
	foreground = '0xdcdcdc'

  [colors.normal]
  black = '0x1d1f21'
  red = '0xcc342b'
  green = '0x198844'
  yellow = '0xfba922'
  blue = '0x3971ed'
  magenta = '0xa36ac7'
  cyan = '0x3971ed'
  white = '0xc5c8c6'

  [colors.bright]
  black = '0x969896'
  red = '0xcc342b'
  green = '0x198844'
  yellow = '0xfba922'
  blue = '0x3971ed'
  magenta = '0xa36ac7'
  cyan = '0x3971ed'
  white = '0xffffff'

	[colors.cursor]
	cursor = '#F2F2F2'
	text = "CellBackground"

[font]
normal = { family = "ComicShannsMono Nerd Font", style = "Regular" }
bold = { family = "ComicShannsMono Nerd Font", style = "Bold" }
size = 11

[window]
decorations = "None"

[env]
TERM = "xterm-256color"

[cursor]
style = { shape = "Block", blinking = "On" }

[terminal.shell]
program = "/etc/profiles/per-user/katob/bin/zsh"

[keyboard]
bindings = [
	{ key = "Right", mods= "Alt", chars= "\u001BF"},
	{ key= "Left", mods= "Alt", chars= "\u001BB"},
	{ key= "Right", mods= "Control", chars= "\u001BF"},
	{ key= "Left", mods= "Control", chars= "\u001BB"},
]

## Alacrity config
