#!/bin/bash


if [ "$1" == "--1337" ]; then
    
    shift
    echo "$*"
    query=$(printf '%s' "$*" | tr ' ' '+' )
    movie=$(curl -s https://1337x.to/search/$query/1/ | grep -Eo "torrent\/[0-9]{7}\/[a-zA-Z0-9?%-]*/" | head -n 1)
    echo $movie
    magnet=$(curl -s https://1337x.to/$movie | grep -Po "magnet:\?xt=urn:btih:[a-zA-Z0-9]*" | head -n 1)
    echo $magnet
    peerflix -l -k $magnet

elif [ "$1" == "--piratebay" ]; then
    
    shift
    QUERY=$(printf '%s' "$*" | sed 's/ /\%20/g')
    MAGNET=$(curl -s "https://thepiratebay.party/search/$QUERY/1/99/0" -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; rv:91.0) Gecko/20100101 Firefox/91.0' | grep -Eo "magnet\:\?[a-zA-Z0-9]{2}=[a-zA-Z0-9]{3}:[a-zA-Z0-9]{4}:[a-zA-Z0-9?%-' '=.+;-]*"| head -n 1)
    peerflix -l -k $MAGNET
fi
