
require("ibl").setup({
	enabled = true,
	debounce = 200,
	indent = {
		char = "|",
		tab_char = "│",
		smart_indent_cap = true,
		priority = 2,
	},
	exclude = {
		filetypes = {
			"", -- for all buffers without a file type
			"alpha",
			"oil",
			"big_file_disabled_ft",
			"dashboard",
			"dotooagenda",
			"flutterToolsOutline",
			"fugitive",
			"git",
			"gitcommit",
			"help",
			"json",
			"log",
			"markdown",
			"NvimTree",
			"Outline",
			"peekaboo",
			"startify",
			"TelescopePrompt",
			"todoist",
			"txt",
			"undotree",
			"vimwiki",
			"vista",
		},
		buftypes = { "terminal", "nofile", "quickfix", "prompt" },
	},
})
