-- require("toggleterm").setup{
--     -- size can be a number or function which is passed the current terminal
--     size = 15,
-- 		direction = 'float',
--     open_mapping = [[<c-t>]],
-- 		float_opts = {
-- 		border = 'double'
-- 	},
--     autochdir = true, -- when neovim changes it current directory the terminal will change it's own when next it's opened
--     shade_terminals = true, -- NOTE: this option takes priority over highlights specified so if you specify Normal highlights you should set this to false
--     start_in_insert = true,
--     insert_mappings = true, -- whether or not the open mapping applies in insert mode
--     terminal_mappings = true, -- whether or not the open mapping applies in the opened terminals
--     persist_size = true,
--     persist_mode = true, -- if set to true (default) the previous terminal mode will be remembered
-- }
-- function _G.set_terminal_keymaps()
--   local opts = {buffer = 0}
--   vim.keymap.set('t', '<esc>', [[<C-\><C-n>]], opts)
--   vim.keymap.set('t', 'jk', [[<C-\><C-n>]], opts)
--   vim.keymap.set('t', '<C-h>', [[<Cmd>wincmd h<CR>]], opts)
--   vim.keymap.set('t', '<C-j>', [[<Cmd>wincmd j<CR>]], opts)
--   vim.keymap.set('t', '<C-k>', [[<Cmd>wincmd k<CR>]], opts)
--   vim.keymap.set('t', '<C-l>', [[<Cmd>wincmd l<CR>]], opts)
-- end

-- vim.cmd('autocmd! TermOpen term://* lua set_terminal_keymaps()')
